### ISSUE TITLE
Error - Purpur 1.18.2

### ISSUE THREAD

**Issue by Adriianh** [TabooLib/zaphkiel#26]
Hey, I'm on 1.18.2, using purpurr. And constantly the server gives this error, when I move, move or use an item and other things.

```
[20:09:15 WARN]: [Zaphkiel] Plugin Zaphkiel v1.7.7 generated an exception while executing task 695
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at ink.ptms.zaphkiel.taboolib.common.platform.ScheduleLoader$inject$1.invoke(ScheduleLoader.kt:22) ~[Zaphkiel-1.7.7.jar:?]
        at ink.ptms.zaphkiel.taboolib.common.platform.ScheduleLoader$inject$1.invoke(ScheduleLoader.kt:22) ~[Zaphkiel-1.7.7.jar:?]
        at ink.ptms.zaphkiel.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[Zaphkiel-1.7.7.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-277]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-277]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-277]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.server.v1_18_R2.ItemStack org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asNMSCopy(org.bukkit.inventory.ItemStack)'
        at ink.ptms.zaphkiel.taboolib.module.nms.NMSGenericImpl.getItemTag(NMSGenericImpl.java:246) ~[?:?]
        at ink.ptms.zaphkiel.taboolib.module.nms.NMSKt.getItemTag(NMS.kt:52) ~[Zaphkiel-1.7.7.jar:?]
        at ink.ptms.zaphkiel.api.ItemStream.<init>(ItemStream.kt:13) ~[Zaphkiel-1.7.7.jar:?]
        at ink.ptms.zaphkiel.ZaphkielAPI.read(ZaphkielAPI.kt:85) ~[Zaphkiel-1.7.7.jar:?]
        at ink.ptms.zaphkiel.item.ItemListener.e(ItemListener.kt:34) ~[Zaphkiel-1.7.7.jar:?]
        ... 12 more
```

**Comment by Bkm016** [comment]
重新下载最新构建

**Comment by Adriianh** [comment]
> 重新下载最新构建 Redownload the latest build, the problem comes from a compatibility bug with 1.18.2

You mean compile it again?, I tried and it gave an error. :(
https://pastes.dev/ho3U5X7JNE
